services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      PG_ADDR: ${PG_ADDR}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_DB: ${PG_DB}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_ADDR: ${REDIS_ADDR}
      GRPC_ADDR: ${GRPC_ADDR}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
    ports:
      - "50051:50051"

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    depends_on:
      - app
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/descriptor/api_descriptor.pb:/etc/envoy/api_descriptor.pb:ro
    ports:
      - "8080:8080"
      - "9901:9901"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
